name: Sugerir uma melhoria
description: Proponha uma nova funcionalidade para o JunimoCheck.
title: "[Ideia]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema essa ideia resolve?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Como você imagina a solução?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas ou detalhes adicionais
